// Generated by Wrangler on Sun Apr 28 2024 16:03:29 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	AZURE_SUBCRIPTION_KEY: string;
	LINE_CHANNEL_ACCESS_TOKEN: string;
	GOOGLE_CREDENTIALS: string;
	GOOGLE_SPREADSHEET_ID: string;
}
